<?php
/** General Functions for Formidable Directory Listings
 *
 * This file contains general functions & shortcodes for Directory Listings.
 *
 * @category FIC
 * @package  Formidable_Directory
 * @author   Pavan Rikhi <pavan@ic.org>
 * @license  GPLv3 https://www.gnu.org/licenses/gpl-3.0.html
 * @link     http://www.ic.org
 */


/* When Draft Listings are updated, send the Directory Manager a notification */
function directory_send_manager_notification($entry_id, $form_id)
{
    $entry = FrmEntry::getOne($entry_id, true);
    $user_not_admin = !current_user_can('edit_plugins');
    if ($form_id == 2 && $entry->metas[920] != 'publish' && $user_not_admin) {
        $MANAGER_EMAIL = "directory@ic.org";
        $listing_name = get_the_title($entry->post_id);
        $edit_link = "https://www.ic.org/wp-admin/admin.php" .
            "?page=formidable-entries&frm_action=edit&id={$entry_id}";
        $subject = "Draft Listing `{$listing_name}` Has Been Updated";
        $message = "{$listing_name} has updated their Directory Listing:\n" .
            "<a href='{$edit_link}' target='_blank'>\n{$edit_link}\n</a>";
        wp_mail($MANAGER_EMAIL, $subject, $message);
    }
}
add_action('frm_after_update_entry', 'directory_send_manager_notification', 10, 2);

/** Show Usernames instead of Display Names for the User ID field */
function directory_usernames_for_user_id($values, $field, $entry_id=false)
{
    $user_field_id = 430;
    if ($field->id == $user_field_id) {
        $users = get_users(array(
            'orderby' => 'login', 'fields' => array('ID', 'user_login')));
        $values['options'] = array();
        foreach ($users as $user) {
            $values['options'][$user->ID] = $user->user_login;
        }
        $values['use_key'] = true;
    }
    return $values;
}
add_filter(
    'frm_setup_new_fields_vars', 'directory_usernames_for_user_id', 20, 2);
add_filter(
    'frm_setup_edit_fields_vars', 'directory_usernames_for_user_id', 20, 3);



/** Show an additional 404 message if the URL is in the 'directory' sub-URI
 * ("ic.org/directory/*").
 *
 * This is used to provide clarity because unapproved and hidden listings
 * return 404 errors.
 *
 * No shortcode parameters are used.
 *
 * @param array $atts Shortcode attributes
 *
 * @return string The additional HTML message to display, or an empty string.
 */
function directory_show_message_if_404_in_directory($atts)
{
    $request_uri = $_SERVER['REQUEST_URI'];
    $sub_uri = "/directory/";
    $request_starts_with_sub_uri = strpos($request_uri, $sub_uri) === 0;

    $message = "<p>If you are looking for a Community in the Directory which has " .
        "not yet been approved, you may see this message. Contact " .
        "<a href=\"mailto:directory@ic.org\">Directory@ic.org</a> with any " .
        "questions.</p>";

    if ($request_starts_with_sub_uri) {
        return $message;
    } else {
        return "";
    }
}
add_shortcode(
    'directory_show_message_if_404_in_directory',
    'directory_show_message_if_404_in_directory'
);


/** Show checkboxes to filter the directory search results page by:
 *
 * - Is Established?
 * - Is Forming?
 * - Visitors Welcome?
 * - Accepting New Members?
 * - Is FIC Member?
 *
 * The checkboxes are generated by modifying the GET parameters of the current
 * URL.
 *
 * @return string HTML containg the checkboxes
 */
function directory_show_search_filters() {
    $filters = array(
        array('param' => 'open_to_visitors', 'value' => 'Yes',
              'text' => 'Visitors Welcome'),
        array('param' => 'open_to_members', 'value' => 'Yes',
              'text' => 'Accepting New Members'),
        array('param' => 'community_status', 'value' => 'Established',
              'text' => 'Established'),
        array('param' => 'community_status', 'value' => 'Forming,%20Re-forming',
              'text' => 'Forming'),
        array('param' => 'fic_member', 'value' => 'Yes', 'text' => 'FIC Member')

    );

    // Check if a filter is used
    foreach ($filters as &$filter) {
        $filter['used'] = array_key_exists($filter['param'], $_GET) &&
            strpos($_GET[$filter['param']], $filter['value']) !== false;
    }

    // Build the HTML
    $checkboxes = array();
    foreach ($filters as &$filter) {
        $new_get = $_GET;
        if ($filter['used']) {
            $new_get[$filter['param']] = FIC_Utils::remove_from_comma_separated_string(
                $filter['value'], $new_get[$filter['param']]
            );
            if ($new_get[$filter['param']] === '') {
                unset($new_get[$filter['param']]);
            }
            $selected = 'checked';
        } else {
            if (array_key_exists($filter['param'], $new_get) &&
                    $new_get[$filter['param']] !== '') {
                $new_get[$filter['param']] .= ',%20' . $filter['value'];
            } else {
                $new_get[$filter['param']] = $filter['value'];
            }
            $selected = '';
        }
        $url = http_build_query($new_get);
        $checkboxes[] = "<input name='{$filter['param']}' type='checkbox'" .
            " onclick=\"window.location='?{$url}';\" $selected>{$filter['text']}";
    }

    $link_html = join(' | ', $checkboxes);

    return "<div style='float:right;'>Filter: {$link_html}</div>" .
        "<div style='clear:both;'></div>";
}
add_shortcode('show_directory_search_filters', 'directory_show_search_filters');


/** Show multiple lists of Communities, drilling down by Country and then
 * State/Province.
 *
 * US Listings are shown first.
 *
 * @return string HTML containing the lists
 */
function directory_show_directory_geo_list() {
    return FIC_Utils::cache_result(function() {
        global $wpdb;

        $directory_form_id = 2;
        $is_public_field_id = 218;
        $country_field_id = 424;
        //$region_field_id = 428;  // Has less entries
        $region_field_id = 816;
        $state_field_id = 815;
        $entries_query = "
            SELECT countries.country, regions.region, states.state
            FROM `{$wpdb->prefix}frm_items` AS entries
            INNER JOIN (SELECT ID, post_status
                        FROM `{$wpdb->prefix}posts`
                        WHERE post_status='publish')
                   AS posts ON posts.ID=entries.post_id
            INNER JOIN (SELECT `item_id`, `meta_value` AS is_public
                        FROM `{$wpdb->prefix}frm_item_metas`
                        WHERE `meta_value`='Yes' AND
                              `field_id`=$is_public_field_id)
                   AS public ON public.item_id=entries.id
            INNER JOIN (SELECT `item_id`, `meta_value` AS country
                        FROM `{$wpdb->prefix}frm_item_metas`
                        WHERE `field_id`=$country_field_id)
                   AS countries ON countries.item_id=entries.id
            LEFT JOIN (SELECT `item_id`, `meta_value` AS region
                       FROM `{$wpdb->prefix}frm_item_metas`
                       WHERE `field_id`=$region_field_id)
                   AS regions ON regions.item_id=entries.id
            LEFT JOIN (SELECT `item_id`, `meta_value` AS state
                       FROM `{$wpdb->prefix}frm_item_metas`
                       WHERE `field_id`=$state_field_id)
                   AS states ON states.item_id=entries.id
            WHERE entries.form_id=$directory_form_id
            ;";
        $entries = $wpdb->get_results($entries_query);

        $countries = array();
        // Count Entries
        foreach ($entries as $entry) {
            if (!array_key_exists($entry->country, $countries)) {
                $countries[$entry->country] = array();
            }
            $region = $entry->country === "United States" ?
                      $entry->state : ucwords($entry->region);
            if (!array_key_exists($region, $countries[$entry->country])) {
                $countries[$entry->country][$region] = 1;
            } else {
                $countries[$entry->country][$region]++;
            }
        }

        // Sort Countries & Regions Alphabetically
        foreach ($countries as &$country) {
            ksort($country);
        }
        ksort($countries);

        // Move US to the Top
        $us = $countries["United States"];
        unset($countries["United States"]);
        $countries = array_merge(array("United States" => $us), $countries);

        // Render as HTML
        $countries_html = '';
        foreach ($countries as $country => $regions) {
            $country_total = array_sum($regions);
            $country_url = "/directory/listings/?cmty-country=$country";
            if ($country === "United States")  {
                $country_class = 'geo-us-state';
                $region_get_parameter = 'cmty-state';
            } else {
                $country_class = 'geo-state';
                $region_get_parameter = 'cmty-prov';
            }
            $region_html = '';
            foreach ($regions as $region => $count) {
                if (empty($region)) {
                    continue;
                } else if ($region === "Kentucky" || $region === "Ohio") {
                    // Start a New Column
                    $region_html .= "</ul></li><li class='$country_class'>
                                     <ul class='$country_class'>";
                }
                $region_url = "$country_url&$region_get_parameter=$region";
                $region_html .= "
                    <li class='geo-state-prov'><a href='$region_url'>
                        $region <span class='geo-count'>($count)</span>
                    </a></li>";
            }

            $countries_html .= "
                <li class='geo-country'><a href='$country_url'>$country
                    <span class='geo-count'>($country_total)</span></a>
                    <ul class='$country_class'>$region_html</ul>
                </li>";
        };

        return '<ul class="geo-country">' . $countries_html . '</ul>';
    }, 'directory_geographical_lists',  7 * 24 * 60 * 60);
}
add_shortcode('show_directory_geo_list', 'directory_show_directory_geo_list');

/** Return the 12 Tribes Child-Discipline Statement
 *
 * @return string HTML containing the statement.
 */
function directory_twelve_tribes_statement() {
    $content = <<<HTML
<h3>Child Rearing Practice of the Twelve Tribes Communities</h3>
<p>We train our children according to the Word of God as recorded in the Bible.
Part of this training is correcting our little ones for errant behavior.
Setting boundaries for our children is an integral part of building good
character into them at a young age. Loving protection for children is of
supreme importance to us. We do not tolerate violence or abuse, whether
physical, psychological, or verbal, nor do we condone disrespectful or
rebellious behavior. We believe it is the God-given right and responsibility of
parents to discipline their children if they are disobedient or disrespectful
to parental guidance.</p>
<p>God is love. He loves children and His word is clear on what it means to
love your child as Proverbs 13:24 says: &ldquo;Whoever spares the rod
<em>hates</em> his son, but he who <em>loves</em> him is diligent to discipline
him.&rdquo; Proverbs 23:13-14 makes it clear that spanking is an act of love to
save your children from the destruction of their souls, and restore them to the
way they should go. &ldquo;Do not withhold discipline from a child; if you
strike him with a rod ... you will save his soul from destruction.&rdquo; And
Proverbs 22:6 states that if you &ldquo;train up a child in the way he should
go, when he is old he will not depart from it.&rdquo;</p>
<p>The Bible does not describe the rod itself, but surely God did not intend
something that would damage a child. We use a thin, reed-like rod, which stings
but causes no damage or injury. We have purposefully chosen this method,
inspired by God’s love, as part of our child rearing practices because His Word
commands us. We see the good fruit in our children, which is recognized all
over the world, even by those who don’t understand it.</p>
<p>Because we love our children, we discipline them only for attitudes and
actions they know to be wrong, and only after the child admits to wrongdoing
and is willing to receive discipline. Godly discipline is always followed by
forgiveness, reconciliation, and encouragement.</p>
<p><em>For a fuller statement about our thinking about Child Discipline, please
visit: <a href="http://twelvetribes.org/articles/on-child-discipline" target='_blank'>
http://twelvetribes.org/articles/on-child-discipline</a>.</em></p>

<p><em>Publisher’s Note: FIC has a policy of not listing communities in our
Directory that advocate violent practices, and there is controversy over
whether the Twelve Tribes Child Discipline practice crosses that line.
While we are convinced of the sincerity of their belief that their practice
is not violent, we are also aware of visitors and ex-members who hold that
it is. In recognition of this controversy, the Twelve Tribes leadership
agreed to have this note referenced as a regular part of each community’s
listing, so that users of the Directory could be more fully informed and
make their own decision about this important matter.</em></p>
HTML;
    return str_replace('  ', ' ', str_replace("\n", ' ', $content));
}
add_shortcode(
    'directory_twelve_tribes_statement', 'directory_twelve_tribes_statement');


?>
